### ISSUE TITLE
Doesn't compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by octylFractal** [mdolidon/endlines#5]
This tool looks really useful, but I can't use it if it doesn't compile :3.

``` bash
$ sudo make install
cc -O3 -Wall -std=c99   -c -o src/walkers.o src/walkers.c
src/walkers.c: In function ‘walk_directory’:
src/walkers.c:203:35: error: ‘DT_DIR’ undeclared (first use in this function)
         } else if(pent->d_type == DT_DIR) {
                                   ^
src/walkers.c:203:35: note: each undeclared identifier is reported only once for each function it appears in
src/walkers.c:205:35: error: ‘DT_REG’ undeclared (first use in this function)
         } else if(pent->d_type == DT_REG) {
                                   ^
src/walkers.c:182:11: warning: variable ‘fake_filenames_array’ set but not used [-Wunused-but-set-variable]
     char* fake_filenames_array[1];              // this holder is a convenience
           ^
make: *** [src/walkers.o] Error 1
```

**Comment by mdolidon** [comment]
Hello, and thanks for this feedback. This is curious, as I've successfully compiled on a Debian station.
I won't come by an Ubuntu station in the times to come, and the laptop I have with me is too weak to run the OS inside a VM. Therefore I'd like to ask you a favour.

Could you please edit the makefile, on line 2 (CFLAGS) add  the -D_BSD_SOURCE flag, and tell me whether it helped ?

**Comment by octylFractal** [comment]
Yes, builds fine now.

**Comment by mdolidon** [comment]
Great stuff, thanks a lot ! I'll put that in the makefile as soon as I get home tonight.
